/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIBuffer */

#ifndef _Included_JNIBuffer
#define _Included_JNIBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIBuffer
 * Method:    createBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_JNIBuffer_createBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNIBuffer
 * Method:    deleteBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIBuffer_deleteBuffers
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
