/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cornell_cs_blog_JNIBlog */

#ifndef _Included_edu_cornell_cs_blog_JNIBlog
#define _Included_edu_cornell_cs_blog_JNIBlog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    initialize
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_initialize
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    createBlock
 * Signature: (Ledu/cornell/cs/sa/VectorClock;J)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_createBlock
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    deleteBlock
 * Signature: (Ledu/cornell/cs/sa/VectorClock;J)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_deleteBlock
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    readBlock
 * Signature: (JJIII[B)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_readBlock
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jbyteArray);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    getNumberOfBytes
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_getNumberOfBytes
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    writeBlock
 * Signature: (Ledu/cornell/cs/sa/VectorClock;JIII[B)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_writeBlock
  (JNIEnv *, jobject, jobject, jlong, jint, jint, jint, jbyteArray);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    since
 * Signature: (JLedu/cornell/cs/sa/VectorClock;)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_since
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    createSnapshot
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_createSnapshot
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    deleteSnapshot
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_edu_cornell_cs_blog_JNIBlog_deleteSnapshot
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    readLocalRTC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_cornell_cs_blog_JNIBlog_readLocalRTC
  (JNIEnv *, jobject);
/*
 * Class:     edu_cornell_cs_blog_JNIBlog
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cornell_cs_blog_JNIBlog_destroy
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
